Give up on any ${path} that is a directory
The author of this commit has waived all copyright and
related or neighboring rights to the extent permitted by
law as described by the CC0 1.0 Universal Public Domain
Dedication. You should have received a copy of the full
dedication along with this commit, typically as a file
named <CC0-1.0.txt>. If not, it may be available at
<https://creativecommons.org/publicdomain/zero/1.0/>.

diff --git a/gatbps.in b/gatbps.in
--- a/gatbps.in
+++ b/gatbps.in
@@ -227,6 +227,22 @@ EOF
       ;;
   esac
 
+  #
+  # Give up on any ${path} that is a directory. Note that getting past
+  # this test does not guarantee that ${path} is not a directory since
+  # the test program could fail for some other reason. POSIX says that
+  # it returns 1 for false and >1 for error, but it seems like a bad
+  # idea to rely on that.
+  #
+
+  if test -d "${path}"; then
+    cat <<EOF >&2
+gatbps: '${file}' is a directory
+EOF
+    gatbps_gave_up_on "${file}"
+    continue
+  fi
+
   name=`expr "X${path}" : 'X.*/\(.*\)' '|' X`
   case "${?}" in
     0)
