Add the VERSION.sh special file
The author of this commit has waived all copyright and
related or neighboring rights to the extent permitted by
law as described by the CC0 1.0 Universal Public Domain
Dedication. You should have received a copy of the full
dedication along with this commit, typically as a file
named <CC0-1.0.txt>. If not, it may be available at
<https://creativecommons.org/publicdomain/zero/1.0/>.

diff --git a/gatbps.in b/gatbps.in
--- a/gatbps.in
+++ b/gatbps.in
@@ -692,6 +692,30 @@ EOF1
             ;;
 
           #(
+            '--help=VERSION.sh'|'--help='*'/VERSION.sh')
+              cat <<EOF1
+Special file: ${fB1}VERSION.sh${fR1}
+
+Try ${fB1}man gatbps${fR1} or ${fB1}info gatbps${fR1} for more information.
+EOF1
+              case "${?}" in
+              #(
+                '0')
+                  :
+                ;;
+              #(
+                *)
+                  cat >&2 <<EOF1
+${fr2}gatbps!${fR2} ${fB2}cat${fR2} failed to read from:
+${fr2}gatbps!${fR2}   1. a here-document
+${fr2}gatbps!${fR2} and write to: standard output
+EOF1
+                  exit '1'
+                ;;
+              esac
+            ;;
+
+          #(
             '--help=bdots.texi'|'--help='*'/bdots.texi')
               cat <<EOF1
 Special file: ${fB1}bdots.texi${fR1}
@@ -1471,6 +1495,7 @@ CC0-1.0-copying.texi
 CC0-1.0-file.txt
 CC0-1.0.txt
 DATE.ac
+VERSION.sh
 bdots.texi
 bothcontents.texi
 contents.texi
@@ -4148,6 +4173,83 @@ dnl dedication along with this file, typically as a file
 dnl named <CC0-1.0.txt>. If not, it may be available at
 dnl <https://creativecommons.org/publicdomain/zero/1.0/>.
 dnl
+EOF1
+            case "${?}" in
+            #(
+              '0')
+                :
+              ;;
+            #(
+              *)
+                cat >&2 <<EOF1
+${fy2}gatbps:${fR2} ${fB2}cat${fR2} failed to read from:
+${fy2}gatbps:${fR2}   1. a here-document
+${fy2}gatbps:${fR2} and write to: ${fB2}${1}${fR2}
+${fy2}gatbps:${fR2} generation failed: ${fB2}${1}${fR2}
+EOF1
+                exit_status='1'
+                break
+              ;;
+            esac
+          ;;
+
+        #(
+          'VERSION.sh'|*'/VERSION.sh')
+            cat >"${safe_1}" <<'EOF1'
+#
+# This file was generated by GATBPS @PACKAGE_VERSION@, which was
+# released on @PACKAGE_DATE@. Before changing it, make sure
+# you're doing the right thing. Depending on how GATBPS
+# is being used, your changes may be automatically lost.
+# A short description of this file follows.
+#
+# Special file: VERSION.sh
+#
+# For more information, see the GATBPS manual.
+#
+
+#
+# This script (VERSION.sh) helps to create a version string for
+# Autotools by using git describe to get the description of HEAD with
+# respect to tags that begin with "v" and a digit. Add this script to
+# your repository and adjust the following code for your configure.ac
+# and Makefile.am files:
+#
+#   AC_INIT([Example],
+#           m4_esyscmd_s([sh VERSION.sh])m4_assert(m4_sysval == 0))
+#
+#   EXTRA_DIST += $(srcdir)/VERSION
+#   EXTRA_DIST += $(srcdir)/VERSION.sh
+#
+# When running in your repository, the script uses git describe and also
+# writes the result to the VERSION file. Elsewhere, the script reads the
+# VERSION file.
+#
+
+set -e
+trap 'rm -f VERSION.tmp' EXIT
+if git ls-files --error-unmatch VERSION.sh >/dev/null 2>&1; then
+  git describe --always --match='v[0-9]*' --tags >VERSION.tmp
+  x=$(sed s/^v// VERSION.tmp)
+  echo "$x" >VERSION.tmp
+  mv VERSION.tmp VERSION
+  echo "$x"
+elif test -f VERSION; then
+  cat VERSION
+else
+  echo 'VERSION.sh: not in repository and VERSION not found' >&2
+  exit 1
+fi
+
+#
+# The authors of this file have waived all copyright and
+# related or neighboring rights to the extent permitted by
+# law as described by the CC0 1.0 Universal Public Domain
+# Dedication. You should have received a copy of the full
+# dedication along with this file, typically as a file
+# named <CC0-1.0.txt>. If not, it may be available at
+# <https://creativecommons.org/publicdomain/zero/1.0/>.
+#
 EOF1
             case "${?}" in
             #(
@@ -7950,6 +8052,53 @@ EOF1
     'yes')
       while :; do
         case "${1}" in
+
+        #(
+          'VERSION.sh'|*'/VERSION.sh')
+
+            case "${1}" in
+            #(
+              'VERSION.sh')
+                prefix=''
+              ;;
+            #(
+              *'/VERSION.sh')
+                x=`"${sed}" "
+s/'/'\\\\\\\\''/g
+1s/^/prefix='/
+\\$s/VERSION.sh\\$/'/
+" <<EOF1
+${1}
+EOF1
+`
+                case "${?}" in
+                #(
+                  '0')
+                    :
+                  ;;
+                #(
+                  *)
+                    cat >&2 <<EOF1
+${fy2}gatbps:${fR2} ${fB2}${sed}${fR2} failed to read from:
+${fy2}gatbps:${fR2}   1. a here-document
+${fy2}gatbps:${fR2} and write to: a command substitution
+${fy2}gatbps:${fR2} recursion failed: ${fB2}${1}${fR2}
+EOF1
+                    exit_status='1'
+                    break
+                  ;;
+                esac
+                eval "${x}"
+              ;;
+            esac
+
+            shift
+
+            set "${prefix}CC0-1.0.txt" "${@AT@}"
+
+            set 'x' "${@AT@}"
+
+          ;;
 
         #(
           'bdots.texi'|*'/bdots.texi')
