Add the DATE.sh special file
The author of this commit has waived all copyright and
related or neighboring rights to the extent permitted by
law as described by the CC0 1.0 Universal Public Domain
Dedication. You should have received a copy of the full
dedication along with this commit, typically as a file
named <CC0-1.0.txt>. If not, it may be available at
<https://creativecommons.org/publicdomain/zero/1.0/>.

diff --git a/gatbps.in b/gatbps.in
--- a/gatbps.in
+++ b/gatbps.in
@@ -692,6 +692,30 @@ EOF1
             ;;
 
           #(
+            '--help=DATE.sh'|'--help='*'/DATE.sh')
+              cat <<EOF1
+Special file: ${fB1}DATE.sh${fR1}
+
+Try ${fB1}man gatbps${fR1} or ${fB1}info gatbps${fR1} for more information.
+EOF1
+              case "${?}" in
+              #(
+                '0')
+                  :
+                ;;
+              #(
+                *)
+                  cat >&2 <<EOF1
+${fr2}gatbps!${fR2} ${fB2}cat${fR2} failed to read from:
+${fr2}gatbps!${fR2}   1. a here-document
+${fr2}gatbps!${fR2} and write to: standard output
+EOF1
+                  exit '1'
+                ;;
+              esac
+            ;;
+
+          #(
             '--help=VERSION.sh'|'--help='*'/VERSION.sh')
               cat <<EOF1
 Special file: ${fB1}VERSION.sh${fR1}
@@ -1495,6 +1519,7 @@ CC0-1.0-copying.texi
 CC0-1.0-file.txt
 CC0-1.0.txt
 DATE.ac
+DATE.sh
 VERSION.sh
 bdots.texi
 bothcontents.texi
@@ -4173,6 +4198,88 @@ dnl dedication along with this file, typically as a file
 dnl named <CC0-1.0.txt>. If not, it may be available at
 dnl <https://creativecommons.org/publicdomain/zero/1.0/>.
 dnl
+EOF1
+            case "${?}" in
+            #(
+              '0')
+                :
+              ;;
+            #(
+              *)
+                cat >&2 <<EOF1
+${fy2}gatbps:${fR2} ${fB2}cat${fR2} failed to read from:
+${fy2}gatbps:${fR2}   1. a here-document
+${fy2}gatbps:${fR2} and write to: ${fB2}${1}${fR2}
+${fy2}gatbps:${fR2} generation failed: ${fB2}${1}${fR2}
+EOF1
+                exit_status='1'
+                break
+              ;;
+            esac
+          ;;
+
+        #(
+          'DATE.sh'|*'/DATE.sh')
+            cat >"${safe_1}" <<'EOF1'
+#
+# This file was generated by GATBPS @PACKAGE_DATE@, which was
+# released on @PACKAGE_DATE@. Before changing it, make sure
+# you're doing the right thing. Depending on how GATBPS
+# is being used, your changes may be automatically lost.
+# A short description of this file follows.
+#
+# Special file: DATE.sh
+#
+# For more information, see the GATBPS manual.
+#
+
+#
+# This script (DATE.sh) helps to create an (AC_)PACKAGE_DATE variable
+# for Autotools by using git log to get the UTC author date of HEAD in
+# YYYY-MM-DD format. Add this script to your repository and adjust the
+# following code for your configure.ac and Makefile.am files:
+#
+#   m4_define([AC_PACKAGE_DATE],
+#             m4_esyscmd_s([sh DATE.sh])m4_assert(m4_sysval == 0))
+#   AC_SUBST([PACKAGE_DATE], 'AC_PACKAGE_DATE')
+#   AC_DEFINE([PACKAGE_DATE], "AC_PACKAGE_DATE")
+#
+#   EXTRA_DIST += $(srcdir)/DATE
+#   EXTRA_DIST += $(srcdir)/DATE.sh
+#
+# When running in your repository, the script uses git log and also
+# writes the result to the DATE file. Elsewhere, the script reads the
+# DATE file.
+#
+
+set -e
+trap 'rm -f DATE.tmp' EXIT
+if git ls-files --error-unmatch DATE.sh >/dev/null 2>&1; then
+  TZ=UTC git log -1 --date=local --pretty=%ad >DATE.tmp
+  x=$(sed 's/... \(...\) \(.*\) ..:..:.. \(....\)/\3-\1-\2/
+           s/Jan/01/; s/Feb/02/; s/Mar/03/; s/Apr/04/
+           s/May/05/; s/Jun/06/; s/Jul/07/; s/Aug/08/
+           s/Sep/09/; s/Oct/10/; s/Nov/11/; s/Dec/12/
+           s/-\(.\)$/-0\1/' DATE.tmp)
+  echo "$x" >DATE.tmp
+  mv DATE.tmp DATE
+  echo "$x"
+elif test -f DATE; then
+  cat DATE
+else
+  echo 'DATE.sh: not in repository and DATE not found' >&2
+  exit 1
+fi
+
+#
+# The authors of this file have waived all copyright and
+# related or neighboring rights to the extent permitted by
+# law as described by the CC0 1.0 Universal Public Domain
+# Dedication. You should have received a copy of the full
+# dedication along with this file, typically as a file
+# named <CC0-1.0.txt>. If not, it may be available at
+# <https://creativecommons.org/publicdomain/zero/1.0/>.
+#
 EOF1
             case "${?}" in
             #(
@@ -8052,6 +8159,53 @@ EOF1
     'yes')
       while :; do
         case "${1}" in
+
+        #(
+          'DATE.sh'|*'/DATE.sh')
+
+            case "${1}" in
+            #(
+              'DATE.sh')
+                prefix=''
+              ;;
+            #(
+              *'/DATE.sh')
+                x=`"${sed}" "
+s/'/'\\\\\\\\''/g
+1s/^/prefix='/
+\\$s/DATE.sh\\$/'/
+" <<EOF1
+${1}
+EOF1
+`
+                case "${?}" in
+                #(
+                  '0')
+                    :
+                  ;;
+                #(
+                  *)
+                    cat >&2 <<EOF1
+${fy2}gatbps:${fR2} ${fB2}${sed}${fR2} failed to read from:
+${fy2}gatbps:${fR2}   1. a here-document
+${fy2}gatbps:${fR2} and write to: a command substitution
+${fy2}gatbps:${fR2} recursion failed: ${fB2}${1}${fR2}
+EOF1
+                    exit_status='1'
+                    break
+                  ;;
+                esac
+                eval "${x}"
+              ;;
+            esac
+
+            shift
+
+            set "${prefix}CC0-1.0.txt" "${@AT@}"
+
+            set 'x' "${@AT@}"
+
+          ;;
 
         #(
           'VERSION.sh'|*'/VERSION.sh')
